//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "trauma_patient")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub admission_number: Option<String>,
    pub emergency_number: Option<String>,
    pub number_of_admission: Option<i32>,
    pub be_in_hospitalization: Option<i8>,
    pub the_green_channel: Option<i8>,
    pub the_soldier: Option<i8>,
    pub be_emergency_case: Option<i8>,
    pub be_transfer_hospital: Option<i8>,
    pub identification_type: Option<i16>,
    pub identification_card: Option<String>,
    pub birthday: Option<String>,
    pub age_unit: Option<i32>,
    pub age: Option<i32>,
    pub gender: Option<i32>,
    pub nation: Option<String>,
    pub occupation: Option<String>,
    pub marriage: Option<String>,
    pub be_admission_time: Option<DateTime>,
    pub be_admission_hospital: Option<String>,
    pub be_admission_department: Option<String>,
    pub region_id: Option<i32>,
    pub nationality: Option<String>,
    pub country: Option<String>,
    pub province: Option<String>,
    pub city: Option<String>,
    pub district: Option<String>,
    pub address: Option<String>,
    pub telephone: Option<String>,
    pub contact: Option<String>,
    pub contact_telephone: Option<String>,
    pub completion_ratio: Option<f32>,
    pub patient_info_completion_ratio: Option<f32>,
    pub created_at: Option<DateTime>,
    pub created_by: Option<String>,
    pub created_dept: Option<String>,
    pub state: Option<String>,
    pub begin_rescue_time: Option<DateTime>,
    pub dilivery_time: Option<DateTime>,
    pub doctor_delivery_time: Option<DateTime>,
    pub updated_by: Option<String>,
    pub updated_at: Option<DateTime>,
    pub approved_by: Option<String>,
    pub approved_at: Option<DateTime>,
    pub deleted: Option<i8>,
    pub deleted_at: Option<DateTime>,
    pub deleted_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
