[package]
name = "api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web   = { workspace = true }
sea-orm     = { workspace = true }
common      = { path = "../common"}